name: LaTeX build
on:
  push:
    branches-ignore:
      - 'gh-action-result/pdflatex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notes-template.tex
      - name: Commit to orphan branch
        run: |
          git checkout --orphan gh-action-result/pdflatex
          git rm -rf .
          git add notes-template.pdf
          git -c user.name='GitHub Action' -c user.email='action@github.com' commit -m "Built paper"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-action-result/pdflatex
          force: true
